"""
Django settings for Media_Manager project.

Generated by 'django-admin startproject' using Django 2.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(__file__))
#BASE_DIR = os.path.dirname(os.path.dirname((os.path.abspath(__file__))))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'z=h&_fygqs3y_xo&ddw!#yam+3z!y4#@*)r6$+^3nyns2@gv=@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ADMIN_ENABLED = False

ALLOWED_HOSTS = ['linux.midtc.com', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Media_Manager.apps.Accounting',
    'Media_Manager.apps.Admin',
    'Media_Manager.apps.Advertising',
    'Media_Manager.apps.BI',
    'Media_Manager.apps.Circulation',
    'Media_Manager.apps.Editorial',
    'Media_Manager.apps.Home',
    'Media_Manager.apps.Production',
#    'markdownx',
    'ckeditor',
    'ckeditor_uploader'
]

CKEDITOR_BASEPATH = '/var/www/Dev_Media_Manager/static/ckeditor/'
CKEDITOR_UPLOAD_PATH = '/var/www/Dev_Media_Manager/static/dist/img/advertising/'

if ADMIN_ENABLED is True:
    INSTALLED_APPS.append('django.contrib.admin')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Media_Manager.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            # '/var/www/Dev_Media_Manager',
            '.',
        ],
        #'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Media_Manager.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    #'default': {
    #    'ENGINE': 'django.db.backends.sqlite3',
    #    'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    #}
    'default': {
        'ENGINE': 'django.db.backends.mysql',
    	'NAME': 'addb', #summaware_demo
    	'USER': 'root',
    	'PASSWORD': '',
    	'HOST': 'localhost',
    	'PORT': '',
        'OPTIONS': {"init_command":"SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED", },
    },
    'midtc': {

        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'amp_raw',
        'USER': 'ricky',
        'PASSWORD': 'Midtc@2230',
        'HOST': 'mysql.midtc.com',
        'PORT': '3306',
    }

}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(os.path.dirname(os.path.dirname(__file__)), 'static/')]
#STATICFILES_DIRS = 'var/www/Dev_Media_Manager/static/'
#STATICFILES_DIRS = [
#    BASE_DIR + "/static"
#]

PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))# + '/../'
#STATIC_ROOT = os.path.join(PROJECT_DIR, 'static')
#STATIC_ROOT = os.path.join(BASE_DIR, 'var/www/Dev_Media_Manager/static/')
STATIC_ROOT = '/var/www/Dev_Media_Manager/static/'

#STATIC_ROOT =  os.path.dirname(os.path.realpath(__file__))#os.path.join(BASE_DIR, 'static')

# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
# 	'handlers': {
#         'console': {
#             'level':'INFO',
#             'class':'logging.FileHandler',
#             'filename': '/var/www/Dev_Media_Manager/tmp/logs/test.log',
#         },
#     },
#     'loggers': {
#         'django': {
#             'handlers':['console'],
#         },
#     }
# }

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'localhost'
EMAIL_PORT = 587
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
EMAIL_USE_TLS = False
DEFAULT_FROM_EMAIL = 'BI <noreply@linux.midtc.com>'